### ISSUE TITLE
Issue when building

### ISSUE THREAD

**Issue by shimwell** [makeclean/occ_faceter#11]
![Screenshot from 2020-10-14 20-41-04](https://user-images.githubusercontent.com/8583900/96037443-c385b800-0e5d-11eb-8cbc-f852ee785d7d.png)

Doe anyone else get this TopoDS_Shape.hxx error or know a fix for it.

**Comment by makeclean** [comment]
Try commenting it out?
________________________________

**Comment by shimwell** [comment]
Ah really sorry, I messed up and was missing a line from the install.
